version: "3.8"

services:
  datasource:
    image: postgres:17-alpine
    container_name: product-service-database_container
    environment:
      POSTGRES_DB: product-service-datasource
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U username -d password" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  product-service:
    container_name: product-service-application_container
    image: antonivan0v/product-service:latest
    ports:
      - "8080:8080"
    depends_on:
      datasource:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_DRIVER : org.postgresql.Driver
      SPRING_DATASOURCE_URL : jdbc:postgresql://datasource:5432/product-service-datasource
      SPRING_DATASOURCE_USERNAME : username
      SPRING_DATASOURCE_PASSWORD : password